# Generated by Django 4.1.3 on 2022-11-10 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('patronymic', models.CharField(max_length=100)),
                ('group', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Visits',
            fields=[
                ('visits_id', models.IntegerField(primary_key=True, serialize=False)),
                ('student_id', models.IntegerField()),
                ('time', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('inout', models.CharField(max_length=100)),
            ],
        ),
    ]
