# Generated by Django 4.1.3 on 2022-11-10 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svisits', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visits',
            name='inout',
        ),
        migrations.RemoveField(
            model_name='visits',
            name='time',
        ),
        migrations.AlterField(
            model_name='visits',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
