# Generated by Django 4.1.3 on 2022-11-10 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svisits', '0002_remove_visits_inout_remove_visits_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visits',
            name='visits_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
